vich_uploader:
    db_driver: orm

    mappings:
        cover_mediaslist:
           uri_prefix: /data-files/medias_list-pictures
           upload_destination: '%kernel.project_dir%/data-files/medias_list-pictures'
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer