vich_uploader:
    db_driver: orm

    mappings:
        cover_mediaslist:
           uri_prefix: /data-files/medias_list-pictures
           upload_destination: '%kernel.project_dir%/public/data-files/medias_list-pictures'
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        picture_artists:
           uri_prefix: /data-files/artist-pictures
           upload_destination: '%kernel.project_dir%/public/data-files/artist-pictures'
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        
        picture_events:
           uri_prefix: /data-files/event-pictures
           upload_destination: '%kernel.project_dir%/public/data-files/event-pictures'
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        picture_clubs:
           uri_prefix: /data-files/club-pictures
           upload_destination: '%kernel.project_dir%/public/data-files/club-pictures'
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        picture_users:
           uri_prefix: /data-files/user-pictures
           upload_destination: '%kernel.project_dir%/public/data-files/user-pictures'
           namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer