vich_uploader:
    db_driver: orm

    mappings:
        cover_mediaslist:
           uri_prefix: '%app.path.cover_mediaslist%'
           upload_destination: '%kernel.project_dir%%app.path.cover_mediaslist%'